version: '3.7'

services:

  # SteamCMD base image
  base:
    image: ${REGISTRY_IMAGE}:base
    build:
      context: image/base
      cache_from:
        - ${REGISTRY_IMAGE}:base

  # SRCDS base image
  srcds:
    image: ${REGISTRY_IMAGE}:srcds
    build:
      context: image/games/base
      cache_from:
        - ${REGISTRY_IMAGE}:srcds
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:base
        - STEAMCMD_SERVER_PORT=27015
        - STEAMCMD_SERVER_MAXPLAYERS="+maxplayers 32"
        - STEAMCMD_SERVER_MINRATE=8000
        - STEAMCMD_SERVER_TICKRATE=128
        - STEAMCMD_SERVER_FPSMAX=300
        - STEAMCMD_SERVER_THREADS=3
        - STEAMCMD_SERVER_SESSION_NAME=srcds

  # HLDS base image
  hlds:
    image: ${REGISTRY_IMAGE}:hlds
    build:
      context: image/games/base
      cache_from:
        - ${REGISTRY_IMAGE}:hlds
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:base
        - STEAMCMD_SERVER_APPID=90
        - STEAMCMD_SERVER_PORT=27015
        - STEAMCMD_SERVER_MAXPLAYERS=32
        - STEAMCMD_SERVER_SESSION_NAME=hlds

  # HLDS image: Half-Life
  hlmp:
    image: ${REGISTRY_IMAGE}:hlmp
    build:
      context: image/games
      dockerfile: Dockerfile.hlds
      cache_from:
        - ${REGISTRY_IMAGE}:hlmp
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:hlds
        - STEAMCMD_SERVER_GAME=valve
        - STEAMCMD_SERVER_MAP=c1a1
        - STEAMCMD_SERVER_SESSION_NAME=hlmp

  # HLDS image: Counter-Strike
  cs:
    image: ${REGISTRY_IMAGE}:cs
    build:
      context: image/games
      dockerfile: Dockerfile.hlds
      cache_from:
        - ${REGISTRY_IMAGE}:cs
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:hlds
        - STEAMCMD_SERVER_GAME=cstrike
        - STEAMCMD_SERVER_MAP=de_dust2
        - STEAMCMD_SERVER_SESSION_NAME=cs

  # HLDS image: Counter-Strike: Condition Zero
  czero:
    image: ${REGISTRY_IMAGE}:czero
    build:
      context: image/games
      dockerfile: Dockerfile.hlds
      cache_from:
        - ${REGISTRY_IMAGE}:czero
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:hlds
        - STEAMCMD_SERVER_APP_CONFIG="+app_set_config 90 mod czero"
        - STEAMCMD_SERVER_GAME=czero
        - STEAMCMD_SERVER_MAP=de_dust2_cz
        - STEAMCMD_SERVER_SESSION_NAME=czero

  # HLDS image: Day of Defeat
  dod:
    image: ${REGISTRY_IMAGE}:dod
    build:
      context: image/games
      dockerfile: Dockerfile.hlds
      cache_from:
        - ${REGISTRY_IMAGE}:dod
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:hlds
        - STEAMCMD_SERVER_APP_CONFIG="+app_set_config 90 mod dod"
        - STEAMCMD_SERVER_GAME=dod
        - STEAMCMD_SERVER_MAP=dod_donner
        - STEAMCMD_SERVER_SESSION_NAME=dod

  # HLDS image: Deathmatch Classic
  dmc:
    image: ${REGISTRY_IMAGE}:dmc
    build:
      context: image/games
      dockerfile: Dockerfile.hlds
      cache_from:
        - ${REGISTRY_IMAGE}:dmc
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:hlds
        - STEAMCMD_SERVER_APP_CONFIG="+app_set_config 90 mod dmc"
        - STEAMCMD_SERVER_GAME=dmc
        - STEAMCMD_SERVER_MAP=dmc_dm2
        - STEAMCMD_SERVER_SESSION_NAME=dmc

  # HLDS image: Half Life: Opposing Force
  op4:
    image: ${REGISTRY_IMAGE}:op4
    build:
      context: image/games
      dockerfile: Dockerfile.hlds
      cache_from:
        - ${REGISTRY_IMAGE}:op4
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:hlds
        - STEAMCMD_SERVER_APP_CONFIG="+app_set_config 90 mod gearbox"
        - STEAMCMD_SERVER_GAME=gearbox
        - STEAMCMD_SERVER_MAP=op4_demise
        - STEAMCMD_SERVER_SESSION_NAME=op4

  # HLDS image: Team Fortress Classic
  tfc:
    image: ${REGISTRY_IMAGE}:tfc
    build:
      context: image/games
      dockerfile: Dockerfile.hlds
      cache_from:
        - ${REGISTRY_IMAGE}:tfc
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:hlds
        - STEAMCMD_SERVER_APP_CONFIG="+app_set_config 90 mod tfc"
        - STEAMCMD_SERVER_GAME=tfc
        - STEAMCMD_SERVER_MAP=2fort
        - STEAMCMD_SERVER_SESSION_NAME=tfc

  # SRCDS image: Black Mesa: Deathmatch
  bms:
    image: ${REGISTRY_IMAGE}:bms
    build:
      context: image/games
      dockerfile: Dockerfile.srcds
      cache_from:
        - ${REGISTRY_IMAGE}:bms
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds
        - STEAMCMD_SERVER_APPID=346680
        - STEAMCMD_SERVER_GAME=bms
        - STEAMCMD_SERVER_MAP=dm_bounce
        - STEAMCMD_SERVER_SESSION_NAME=bms

  # SRCDS image: Counter-Strike: Source
  css:
    image: ${REGISTRY_IMAGE}:css
    build:
      context: image/games
      dockerfile: Dockerfile.srcds
      cache_from:
        - ${REGISTRY_IMAGE}:css
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds
        - STEAMCMD_SERVER_APPID=232330
        - STEAMCMD_SERVER_GAME=cstrike
        - STEAMCMD_SERVER_MAP=de_dust2
        - STEAMCMD_SERVER_TICKRATE=67
        - STEAMCMD_SERVER_SESSION_NAME=css

  # SRCDS image: Counter-Strike: Global Offensive
  csgo:
    image: ${REGISTRY_IMAGE}:csgo
    build:
      context: image/games
      dockerfile: Dockerfile.srcds
      cache_from:
        - ${REGISTRY_IMAGE}:csgo
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds
        - STEAMCMD_SERVER_APPID=740
        - STEAMCMD_SERVER_GAME=csgo
        - STEAMCMD_SERVER_MAP=de_dust2
        - STEAMCMD_SERVER_MAXPLAYERS="-maxplayers_override 32"
        - STEAMCMD_SERVER_SESSION_NAME=csgo

  # SRCDS image: Day of Defeat: Source
  dods:
    image: ${REGISTRY_IMAGE}:dods
    build:
      context: image/games
      dockerfile: Dockerfile.srcds
      cache_from:
        - ${REGISTRY_IMAGE}:dods
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds
        - STEAMCMD_SERVER_APPID=232290
        - STEAMCMD_SERVER_GAME=dod
        - STEAMCMD_SERVER_MAP=dod_palermo
        - STEAMCMD_SERVER_SESSION_NAME=dods

  # SRCDS image: Left 4 Dead
  l4d:
    image: ${REGISTRY_IMAGE}:l4d
    build:
      context: image/games
      dockerfile: Dockerfile.srcds
      cache_from:
        - ${REGISTRY_IMAGE}:l4d
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds
        - STEAMCMD_SERVER_APPID=222840
        - STEAMCMD_SERVER_GAME=left4dead
        - STEAMCMD_SERVER_MAP=l4d_hospital01_apartment
        - STEAMCMD_SERVER_SESSION_NAME=left4dead

  # SRCDS image: Left 4 Dead 2
  l4d2:
    image: ${REGISTRY_IMAGE}:l4d2
    build:
      context: image/games
      dockerfile: Dockerfile.srcds
      cache_from:
        - ${REGISTRY_IMAGE}:l4d2
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds
        - STEAMCMD_SERVER_APPID=222860
        - STEAMCMD_SERVER_GAME=left4dead2
        - STEAMCMD_SERVER_MAP=c2m1_highway
        - STEAMCMD_SERVER_SESSION_NAME=left4dead2

  # SRCDS image: Garray's Mod
  gm:
    image: ${REGISTRY_IMAGE}:gm
    build:
      context: image/games
      dockerfile: Dockerfile.srcds
      cache_from:
        - ${REGISTRY_IMAGE}:gm
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds
        - STEAMCMD_SERVER_APPID=4020
        - STEAMCMD_SERVER_GAME=garrysmod
        - STEAMCMD_SERVER_MAP=gm_construct
        - STEAMCMD_SERVER_SESSION_NAME=garrysmod

  # SRCDS image: Half Life 2: Deathmatch
  hl2mp:
    image: ${REGISTRY_IMAGE}:hl2mp
    build:
      context: image/games
      dockerfile: Dockerfile.srcds
      cache_from:
        - ${REGISTRY_IMAGE}:hl2mp
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds
        - STEAMCMD_SERVER_APPID=232370
        - STEAMCMD_SERVER_GAME=hl2mp
        - STEAMCMD_SERVER_MAP=dm_lockdown
        - STEAMCMD_SERVER_SESSION_NAME=hl2mp
