version: '3.7'
name: steamcmd

services:
  ###
  ### Base images
  ###

  base-sniper:
    image: ${DOCKER_REPO_NAMESPACE}:base-sniper
    build:
      context: ./image/base
      dockerfile: Dockerfile
      args:
        # BUILDKIT_INLINE_CACHE: '1'
        STEAMRT_PLATFORM_VARIANT: sniper
        STEAMRT_PLATFORM_VERSION: 0.20231002.61997
      cache_from:
        - ${DOCKER_REGISTRY_NAME}/${DOCKER_REPO_NAMESPACE}:base-soldier-latest
        - docker.io/${DOCKER_REPO_NAMESPACE}:base-soldier-latest
        - ${DOCKER_REPO_NAMESPACE}:base-soldier

  base-soldier:
    image: ${DOCKER_REPO_NAMESPACE}:base-soldier
    build:
      context: ./image/base
      dockerfile: Dockerfile
      args:
        # BUILDKIT_INLINE_CACHE: '1'
        STEAMRT_PLATFORM_VARIANT: soldier
        STEAMRT_PLATFORM_VERSION: 0.20231002.61993
      cache_from:
        - ${DOCKER_REGISTRY_NAME}/${DOCKER_REPO_NAMESPACE}:base-sniper-latest
        - docker.io/${DOCKER_REPO_NAMESPACE}:base-sniper-latest
        - ${DOCKER_REPO_NAMESPACE}:base-sniper

  ###
  ### Production images
  ###

  src2:
    image: ${DOCKER_REPO_NAMESPACE}:src2
    build:
      context: ./image/src2
      dockerfile: Dockerfile
      args:
        # BUILDKIT_INLINE_CACHE: '1'
        REGISTRY_BASE_IMAGE: ${DOCKER_REPO_NAMESPACE}:base-sniper
      cache_from:
        - ${DOCKER_REGISTRY_NAME}/${DOCKER_REPO_NAMESPACE}:base-sniper-latest
        - docker.io/${DOCKER_REPO_NAMESPACE}:base-sniper-latest
        - ${DOCKER_REPO_NAMESPACE}:base-sniper

  csgo:
    image: ${DOCKER_REPO_NAMESPACE}:csgo
    build:
      context: ./image/srcds
      dockerfile: Dockerfile
      args:
        # BUILDKIT_INLINE_CACHE: '1'
        REGISTRY_BASE_IMAGE: ${DOCKER_REPO_NAMESPACE}:base-sniper
        STEAMCMD_SERVER_MAXPLAYERS: '"-maxplayers_override 32"'
        STEAMCMD_SERVER_SESSION_NAME: csgo
      cache_from:
        - ${DOCKER_REGISTRY_NAME}/${DOCKER_REPO_NAMESPACE}:base-sniper-latest
        - docker.io/${DOCKER_REPO_NAMESPACE}:base-sniper-latest
        - ${DOCKER_REPO_NAMESPACE}:base-sniper

  srcds:
    image: ${DOCKER_REPO_NAMESPACE}:srcds
    build:
      context: ./image/srcds
      dockerfile: Dockerfile
      args:
        # BUILDKIT_INLINE_CACHE: '1'
        REGISTRY_BASE_IMAGE: ${DOCKER_REPO_NAMESPACE}:base-sniper
      cache_from:
        - ${DOCKER_REGISTRY_NAME}/${DOCKER_REPO_NAMESPACE}:base-sniper-latest
        - docker.io/${DOCKER_REPO_NAMESPACE}:base-sniper-latest
        - ${DOCKER_REPO_NAMESPACE}:base-sniper
        
  hlds:
    image: ${DOCKER_REPO_NAMESPACE}:hlds
    build:
      context: ./image/hlds
      dockerfile: Dockerfile
      args:
        # BUILDKIT_INLINE_CACHE: '1'
        REGISTRY_BASE_IMAGE: ${DOCKER_REPO_NAMESPACE}:base-soldier
      cache_from:
        - ${DOCKER_REGISTRY_NAME}/${DOCKER_REPO_NAMESPACE}:base-soldier-latest
        - docker.io/${DOCKER_REPO_NAMESPACE}:base-soldier-latest
        - ${DOCKER_REPO_NAMESPACE}:base-soldier
        