version: '3.7'

services:
  base:
    image: ${REGISTRY_IMAGE}:base
    build:
      context: image/base
      cache_from:
        - ${REGISTRY_IMAGE}:base

  srcds:
    image: ${REGISTRY_IMAGE}:srcds
    build:
      context: image/srcds
      cache_from:
        - ${REGISTRY_IMAGE}:srcds
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:base

  hlds:
    image: ${REGISTRY_IMAGE}:hlds
    build:
      context: image/hlds
      cache_from:
        - ${REGISTRY_IMAGE}:hlds
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:base

  cs:
    image: ${REGISTRY_IMAGE}:cs
    build:
      context: image/games/hlds/cs
      cache_from:
        - ${REGISTRY_IMAGE}:cs
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:hlds

  bms:
    image: ${REGISTRY_IMAGE}:bms
    build:
      context: image/games/srcds/bms
      cache_from:
        - ${REGISTRY_IMAGE}:bms
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds

  css:
    image: ${REGISTRY_IMAGE}:css
    build:
      context: image/games/srcds/css
      cache_from:
        - ${REGISTRY_IMAGE}:css
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds

  csgo:
    image: ${REGISTRY_IMAGE}:csgo
    build:
      context: image/games/srcds/csgo
      cache_from:
        - ${REGISTRY_IMAGE}:csgo
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds

  dods:
    image: ${REGISTRY_IMAGE}:dods
    build:
      context: image/games/srcds/dods
      cache_from:
        - ${REGISTRY_IMAGE}:dods
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds

  l4d:
    image: ${REGISTRY_IMAGE}:l4d
    build:
      context: image/games/srcds/l4d
      cache_from:
        - ${REGISTRY_IMAGE}:l4d
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds

  l4d2:
    image: ${REGISTRY_IMAGE}:l4d2
    build:
      context: image/games/srcds/l4d2
      cache_from:
        - ${REGISTRY_IMAGE}:l4d2
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds

  gm:
    image: ${REGISTRY_IMAGE}:gm
    build:
      context: image/games/srcds/gm
      cache_from:
        - ${REGISTRY_IMAGE}:gm
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds

  hl2mp:
    image: ${REGISTRY_IMAGE}:hl2mp
    build:
      context: image/games/srcds/hl2mp
      cache_from:
        - ${REGISTRY_IMAGE}:hl2mp
      args:
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:srcds
