version: '3.7'

services:
  # Legacy base image
  base-legacy:
    image: ${REGISTRY_IMAGE}:base-legacy
    build:
      context: image/base
      args:
        - BUILDKIT_INLINE_CACHE=1
        - STEAMRT_PLATFORM_VARIANT=soldier
        - STEAMRT_PLATFORM_VERSION=0.20230808.56728
      cache_from:
        - ghcr.io/thetredev/steamcmd:base-legacy-latest
        - ${REGISTRY_IMAGE}:base-legacy

  # CS:GO base image
  base-csgo:
    image: ${REGISTRY_IMAGE}:base-csgo
    build:
      context: image/base
      args:
        - BUILDKIT_INLINE_CACHE=1
        - STEAMRT_PLATFORM_VARIANT=sniper
        - STEAMRT_PLATFORM_VERSION=0.20230808.56699
      cache_from:
        - ghcr.io/thetredev/steamcmd:base-csgo-latest
        - ${REGISTRY_IMAGE}:base-csgo

  # HLDS image
  hlds:
    image: ${REGISTRY_IMAGE}:hlds
    build:
      context: image/hlds
      args:
        - BUILDKIT_INLINE_CACHE=1
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:base-legacy
        - STEAMCMD_SERVER_APPID=90
        - STEAMCMD_SERVER_PORT=27015
        - STEAMCMD_SERVER_MAXPLAYERS=32
        - STEAMCMD_SERVER_SESSION_NAME=hlds
      cache_from:
        - ghcr.io/thetredev/steamcmd:base-hlds-latest
        - ${REGISTRY_IMAGE}:hlds

  # SRCDS image
  srcds:
    image: ${REGISTRY_IMAGE}:srcds
    build:
      context: image/srcds
      args:
        - BUILDKIT_INLINE_CACHE=1
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:base-legacy
        - STEAMCMD_SERVER_PORT=27015
        - STEAMCMD_SERVER_MAXPLAYERS="+maxplayers 32"
        - STEAMCMD_SERVER_MINRATE=8000
        - STEAMCMD_SERVER_TICKRATE=128
        - STEAMCMD_SERVER_FPSMAX=300
        - STEAMCMD_SERVER_THREADS=3
        - STEAMCMD_SERVER_SESSION_NAME=srcds
      cache_from:
        - ghcr.io/thetredev/steamcmd:base-srcds-latest
        - ${REGISTRY_IMAGE}:srcds

  # CS:GO image
  csgo:
    image: ${REGISTRY_IMAGE}:csgo
    build:
      context: image/srcds
      args:
        - BUILDKIT_INLINE_CACHE=1
        - REGISTRY_BASE_IMAGE=${REGISTRY_IMAGE}:base-csgo
        - STEAMCMD_SERVER_PORT=27015
        - STEAMCMD_SERVER_MAXPLAYERS="-maxplayers_override 32"
        - STEAMCMD_SERVER_MINRATE=8000
        - STEAMCMD_SERVER_TICKRATE=128
        - STEAMCMD_SERVER_FPSMAX=300
        - STEAMCMD_SERVER_THREADS=3
        - STEAMCMD_SERVER_SESSION_NAME=csgo
      cache_from:
        - ghcr.io/thetredev/steamcmd:base-csgo-latest
        - ${REGISTRY_IMAGE}:srcds
