version: '3.7'

networks:
  hlds:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 0

# HLDS image: Counter-Strike (SSH enabled)
services:
  cs:
    image: ghcr.io/thetredev/steamcmd:hlds-latest
    container_name: cs
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TIME_ZONE: Europe/Berlin
      STEAMCMD_UID: 1000
      STEAMCMD_GID: 5000
      STEAMCMD_SERVER_GAME: cstrike
      STEAMCMD_SERVER_MAP: de_dust2
      STEAMCMD_SERVER_SESSION_NAME: cs
      STEAMCMD_SSH_SERVER_ENABLE: 1
      STEAMCMD_SSH_AUTHORIZED_KEYS: "<your SSH public keys separated by newline and base64 encoded>"
    ports:
      # SSH port
      - "2244:22/tcp"
      # HLDS port
      - "27015:27015/udp"
      # enable the TCP one for RCON
      #- "27015:27015/tcp"
    volumes:
      # SSH host keys
      - ./cs-ssh:/opt/ssh
      # game server files
      - ./cs:/var/lib/steamcmd/server
      # shared tmux socket directory:
      #- /tmp/steamcmd:/tmp/steamcmd
    networks:
      - hlds
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    ulimits:
      nofile:
        soft: 2048
        hard: 2048
