version: '3.7'

networks:
  hlds:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 0

services:
  czero:
    image: ghcr.io/thetredev/steamcmd:czero-latest
    container_name: czero
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TIME_ZONE: Europe/Berlin
      STEAMCMD_UID: 1000
      STEAMCMD_GID: 5000
    ports:
      - "27015:27015/udp"
      # enable the TCP one for RCON
      #- "27015:27015/tcp"
    volumes:
      # game server files
      - ./czero:/var/lib/steamcmd/server
      # shared tmux socket directory:
      #- /tmp/steamcmd:/tmp/steamcmd
    networks:
      - hlds
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    ulimits:
      nofile:
        soft: 2048
        hard: 2048
