version: '3.7'

networks:
  hlds:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 0

# HLDS image: Half Life: Opposing Force
services:
  op4:
    image: ghcr.io/thetredev/steamcmd:hlds-latest
    container_name: op4
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TIME_ZONE: Europe/Berlin
      STEAMCMD_UID: 1000
      STEAMCMD_GID: 5000
      STEAMCMD_SERVER_APP_CONFIG: "+app_set_config 90 mod gearbox"
      STEAMCMD_SERVER_GAME: gearbox
      STEAMCMD_SERVER_MAP: op4_demise
      STEAMCMD_SERVER_SESSION_NAME: op4
    ports:
      - "27015:27015/udp"
      # enable the TCP one for RCON
      #- "27015:27015/tcp"
    volumes:
      # game server files
      - ./op4:/var/lib/steamcmd/server
      # shared tmux socket directory:
      #- /tmp/steamcmd:/tmp/steamcmd
    networks:
      - hlds
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    ulimits:
      nofile:
        soft: 2048
        hard: 2048
