version: '3.7'

services:
  css:
    image: ghcr.io/thetredev/steamcmd:css-latest
    container_name: css
    stdin_open: true
    tty: true
    environment:
      TIME_ZONE: Europe/Berlin
      STEAMCMD_UID: 1000
      STEAMCMD_GID: 5000
    ports:
      - "27015:27015/udp"
      # enable the TCP one for RCON
      #- "27015:27015/tcp"
    volumes:
      - ./css:/var/lib/steamcmd/server
    ulimits:
      nofile:
        soft: 2048
        hard: 2048
