version: '3.7'

networks:
  srcds:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 0

# SRCDS image: Day of Defeat: Source
services:
  dods:
    image: ghcr.io/thetredev/steamcmd:srcds-latest
    container_name: dods
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TIME_ZONE: Europe/Berlin
      STEAMCMD_UID: 1000
      STEAMCMD_GID: 5000
      STEAMCMD_SERVER_APPID: 232290
      STEAMCMD_SERVER_GAME: dod
      STEAMCMD_SERVER_MAP: dod_palermo
      STEAMCMD_SERVER_SESSION_NAME: dods
    ports:
      - "27015:27015/udp"
      # enable the TCP one for RCON
      #- "27015:27015/tcp"
    volumes:
      # game server files
      - ./dods:/var/lib/steamcmd/server
      # shared tmux socket directory:
      #- /tmp/steamcmd:/tmp/steamcmd
    networks:
      - srcds
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    ulimits:
      nofile:
        soft: 2048
        hard: 2048
