version: '3.7'

networks:
  srcds:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 0

# SRCDS image: Garray's Mod
services:
  gm:
    image: ghcr.io/thetredev/steamcmd:srcds-latest
    container_name: gm
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TIME_ZONE: Europe/Berlin
      STEAMCMD_UID: 1000
      STEAMCMD_GID: 5000
      STEAMCMD_SERVER_APPID: 4020
      STEAMCMD_SERVER_GAME: garrysmod
      STEAMCMD_SERVER_MAP: gm_construct
      STEAMCMD_SERVER_SESSION_NAME: garrysmod
    ports:
      - "27015:27015/udp"
      # enable the TCP one for RCON
      #- "27015:27015/tcp"
    volumes:
      # game server files
      - ./gm:/var/lib/steamcmd/server
      # shared tmux socket directory:
      #- /tmp/steamcmd:/tmp/steamcmd
    networks:
      - srcds
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    ulimits:
      nofile:
        soft: 2048
        hard: 2048
