name: Docker build

on:
  push:
    branches-ignore:
      - main

jobs:
  build-scan:
    uses: thetredev/steamcmd/.github/workflows/build-scan-push-tag.yml@main
    with:
      push: false
      tag: false
    secrets: inherit
