name: Docker build and publish latest

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  REGISTRY_IMAGE: "${{ github.repository_owner }}/${{ github.event.repository.name }}"
  GHCR_PREFIX: "ghcr.io"
  DOCKER_HUB_PREFIX: "docker.io"
  DOCKER_IMAGE_BASE_ORDER: "base srcds hlds"
  DOCKER_RETAG_SH: ".github/scripts/docker_retag.sh"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_ACCESS }}" | docker login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push latest base images
        run: |
          for docker_base_image_type in ${DOCKER_IMAGE_BASE_ORDER}; do
            docker-compose build ${docker_base_image_type}

            bash ${DOCKER_RETAG_SH} \
              ${REGISTRY_IMAGE}:${docker_base_image_type} \
              ${GHCR_PREFIX}/${REGISTRY_IMAGE}:${docker_base_image_type}-latest \
              ${DOCKER_HUB_PREFIX}/${REGISTRY_IMAGE}:${docker_base_image_type}-latest
          done

      - name: Build and push latest HLDS-based game images
        run: |
          for docker_hlds_game in $(ls image/games/hlds); do
            docker-compose build ${docker_hlds_game}

            bash ${DOCKER_RETAG_SH} \
              ${REGISTRY_IMAGE}:${docker_hlds_game} \
              ${GHCR_PREFIX}/${REGISTRY_IMAGE}:${docker_hlds_game}-latest \
              ${DOCKER_HUB_PREFIX}/${REGISTRY_IMAGE}:${docker_hlds_game}-latest
          done

      - name: Build and push latest SRCDS-based game images
        run: |
          for docker_srcds_game in $(ls image/games/srcds); do
            docker-compose build ${docker_srcds_game}

            bash ${DOCKER_RETAG_SH} \
              ${REGISTRY_IMAGE}:${docker_srcds_game} \
              ${GHCR_PREFIX}/${REGISTRY_IMAGE}:${docker_srcds_game}-latest \
              ${DOCKER_HUB_PREFIX}/${REGISTRY_IMAGE}:${docker_srcds_game}-latest
          done

      - name: Run Trivy vulnerability scanner - SRCDS image
        uses: aquasecurity/trivy-action@4b9b6fb4ef28b31450391a93ade098bb00de584e
        with:
          image-ref: "${{ env.GHCR_PREFIX }}:srcds-latest"
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
