name: Docker build and publish latest

on:
  push:
    branches:
      - main

jobs:
  push:
    uses: thetredev/steamcmd/.github/workflows/build-scan-push-tag.yml@main
    with:
      push: true
      tag: false
    secrets: inherit
