name: Docker tag release

on:
  push:
    tags:
      - '**'

jobs:
  tag:
    uses: thetredev/steamcmd/.github/workflows/build-push-tag.yml@main
    with:
      push: false
      tag: true
    secrets: inherit
