name: Docker build

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

env:
  REGISTRY_IMAGE: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-build"
  DOCKER_IMAGE_TYPES: "base srcds css csgo"

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          for docker_image_type in ${DOCKER_IMAGE_TYPES}; do
            docker-compose build ${docker_image_type}
          done
