name: Docker build

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

env:
  DOCKER_BUILDKIT: 1
  REGISTRY_IMAGE: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-build"
  DOCKER_IMAGE_BASE_ORDER: "base srcds"

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build base images
        run: |
          for docker_base_image_type in ${DOCKER_IMAGE_BASE_ORDER}; do
            docker-compose build ${docker_base_image_type}
          done

      - name: Build SRCDS-based game images
        run: |
          for docker_srcds_game in $(ls image/games/srcds); do
            docker-compose build ${docker_srcds_game}
          done
