name: Docker build and publish latest

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  REGISTRY_IMAGE: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
  DOCKER_IMAGE_BASE_ORDER: "base srcds"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push latest base images
        run: |
          for docker_base_image_type in ${DOCKER_IMAGE_BASE_ORDER}; do
            docker-compose build ${docker_base_image_type}

            src_docker_image=${REGISTRY_IMAGE}:${docker_base_image_type}
            dst_docker_image=${REGISTRY_IMAGE}:${docker_base_image_type}-latest

            docker tag ${src_docker_image} ${dst_docker_image}
            docker push ${dst_docker_image}
          done

      - name: Build and push latest SRCDS-based game images
        run: |
          for docker_srcds_game in $(ls image/games/srcds); do
            docker-compose build ${docker_srcds_game}

            src_docker_image=${REGISTRY_IMAGE}:${docker_srcds_game}
            dst_docker_image=${REGISTRY_IMAGE}:${docker_srcds_game}-latest

            docker tag ${src_docker_image} ${dst_docker_image}
            docker push ${dst_docker_image}
          done

      - name: Run Trivy vulnerability scanner - SRCDS image
        uses: aquasecurity/trivy-action@4b9b6fb4ef28b31450391a93ade098bb00de584e
        with:
          image-ref: "${{ env.REGISTRY_IMAGE }}:srcds-latest"
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
